/**
 * One-click report: a self-contained HTML document (embedded SVG charts + tables +
 * methods paragraph) that a lab can open, read, and print to PDF. Built in the
 * browser so Observable Plot can render the charts to inline SVG.
 */
import * as Plot from "@observablehq/plot";
import type { WorkspaceEntry } from "./types.ts";
import { methodsText } from "./log.ts";

function svgOf(options: Plot.PlotOptions): string {
  const node = Plot.plot(options);
  const svg = node instanceof SVGElement ? node : node.querySelector("svg");
  const html = (svg ?? node).outerHTML;
  node.remove?.();
  return html;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function buildReportHtml(entry: WorkspaceEntry): string {
  const per = entry.perResidue;
  const scatter = svgOf({
    width: 520, height: 300, marginLeft: 50, marginBottom: 40,
    x: { label: "pLDDT →", domain: [0, 100], grid: true },
    y: { label: "↑ deviation (Å)", grid: true },
    marks: [Plot.dot(per, { x: "plddt", y: "deviation", fill: "deviation", r: 2.5 }), Plot.ruleY([0])],
  });
  const track = svgOf({
    width: 520, height: 200, marginLeft: 50, marginBottom: 40,
    x: { label: "UniProt residue →", grid: true },
    y: { label: "↑ deviation (Å)", grid: true },
    marks: [Plot.areaY([...per].sort((a, b) => a.uniprotNum - b.uniprotNum), { x: "uniprotNum", y: "deviation", fill: "#dbeafe" }),
      Plot.lineY([...per].sort((a, b) => a.uniprotNum - b.uniprotNum), { x: "uniprotNum", y: "deviation", stroke: "#2563eb" })],
  });

  const rho = Number.isNaN(entry.plddtErrorSpearman) ? "n/a" : entry.plddtErrorSpearman.toFixed(3);
  const metrics: Array<[string, string]> = [
    ["RMSD", `${entry.rmsd.toFixed(2)} Å`],
    ["TM-score", entry.tmScore.toFixed(3)],
    ["GDT-TS", entry.gdtTs.toFixed(3)],
    ["pLDDT–error ρ", rho],
    ["Matched residues", String(entry.nMatched)],
  ];

  return `<!doctype html><html><head><meta charset="utf-8"><title>OpenFoldUI report — ${esc(entry.proteinName)}</title>
<style>
  body { font-family: system-ui, sans-serif; color: #0f172a; max-width: 760px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
  h1 { font-size: 1.5rem; margin-bottom: 0.2rem; } .muted { color: #64748b; }
  table { border-collapse: collapse; margin: 1rem 0; } td, th { border: 1px solid #e2e8f0; padding: 0.4rem 0.9rem; text-align: left; }
  .metrics td:first-child { font-weight: 600; } .figs { display: flex; flex-wrap: wrap; gap: 1rem; }
  .methods { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; }
  .warn { color: #92400e; } footer { margin-top: 2rem; color: #94a3b8; font-size: 0.8rem; }
  @media print { body { margin: 0; } }
</style></head><body>
  <h1>${esc(entry.proteinName)}</h1>
  <div class="muted">${esc(entry.uniprot)} vs ${esc(entry.pdbId)} · chain ${esc(entry.chain)} · ${new Date(entry.createdAt).toDateString()}</div>
  <table class="metrics"><tbody>${metrics.map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join("")}</tbody></table>
  ${entry.warnings.length ? `<p class="warn"><strong>Warnings:</strong><br>${entry.warnings.map(esc).join("<br>")}</p>` : ""}
  <h2>Figures</h2>
  <div class="figs"><div>${scatter}</div><div>${track}</div></div>
  <h2>Methods</h2>
  <div class="methods">${esc(methodsText(entry))}</div>
  ${entry.notes ? `<h2>Notes</h2><p>${esc(entry.notes)}</p>` : ""}
  <footer>Generated by OpenFoldUI — open this file and print to PDF.</footer>
</body></html>`;
}

export function downloadReport(entry: WorkspaceEntry): void {
  const html = buildReportHtml(entry);
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${entry.uniprot}_${entry.pdbId}_report.html`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
